# Generated by Django 3.0.8 on 2021-03-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=1200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=500, null=True)),
                ('specialInstructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
