# Generated by Django 3.0.8 on 2021-03-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_billingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='static/images/'),
        ),
    ]
